import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { unitShort, isLowStock } from "@/lib/money";

interface Item {
  id: string;
  name: string;
  category: string;
  quantity: number;
  quantityAdded?: number;
  quantityUsed?: number;
  unitType?: string;
  minQuantity: number;
  supplierId?: string | null;
}
interface Supplier { id: string; name: string }

export function generateInventoryPDF(opts: {
  items: Item[];
  suppliers: Record<string, Supplier>;
  systemName?: string;
  organization?: string;
}) {
  const { items, suppliers, systemName = "Stock Management System", organization } = opts;
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const now = new Date();

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(systemName, 40, 50);
  doc.setFontSize(13);
  doc.setFont("helvetica", "normal");
  doc.text("Inventory Report", 40, 70);
  doc.setFontSize(10);
  doc.setTextColor(110);
  if (organization) doc.text(organization, 40, 86);
  doc.text(`Generated: ${now.toLocaleString()}`, pageW - 40, 50, { align: "right" });
  doc.setDrawColor(200);
  doc.line(40, 96, pageW - 40, 96);
  doc.setTextColor(0);

  // Items table
  const rows = items.map((i) => [
    i.name,
    i.category || "—",
    (i.supplierId && suppliers[i.supplierId]?.name) || "—",
    String(Number(i.quantityAdded ?? 0)),
    String(Number(i.quantityUsed ?? 0)),
    String(Number(i.quantity ?? 0)),
    unitShort(i.unitType) || "—",
  ]);

  autoTable(doc, {
    startY: 110,
    head: [["Item", "Category", "Supplier", "Added", "Used", "Remaining", "Unit"]],
    body: rows,
    styles: { fontSize: 9, cellPadding: 6, lineColor: [220, 220, 220], lineWidth: 0.5 },
    headStyles: { fillColor: [33, 37, 41], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 249, 250] },
    columnStyles: {
      3: { halign: "right" },
      4: { halign: "right" },
      5: { halign: "right" },
    },
    didParseCell: (data) => {
      if (data.section === "body") {
        const it = items[data.row.index];
        if (it && isLowStock(it)) {
          data.cell.styles.fillColor = [255, 243, 205];
        }
      }
    },
    margin: { left: 40, right: 40 },
  });

  // Summary
  // @ts-ignore
  let y = (doc as any).lastAutoTable.finalY + 24;
  if (y > pageH - 140) { doc.addPage(); y = 50; }

  const lowItems = items.filter(isLowStock);
  const byUnit = items.reduce<Record<string, number>>((acc, i) => {
    const u = unitShort(i.unitType) || "—";
    acc[u] = (acc[u] || 0) + Number(i.quantity || 0);
    return acc;
  }, {});

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Summary", 40, y);
  y += 16;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Total items: ${items.length}`, 40, y); y += 14;
  doc.text(`Low stock items: ${lowItems.length}`, 40, y); y += 14;
  const unitLine = Object.entries(byUnit).map(([u, q]) => `${q} ${u}`).join("   |   ");
  if (unitLine) { doc.text(`Total quantity by unit: ${unitLine}`, 40, y); y += 18; }

  if (lowItems.length) {
    doc.setFont("helvetica", "bold");
    doc.text("Low stock items", 40, y); y += 6;
    doc.setFont("helvetica", "normal");
    autoTable(doc, {
      startY: y + 6,
      head: [["Item", "Category", "Remaining", "Unit"]],
      body: lowItems.map((i) => [i.name, i.category || "—", String(Number(i.quantity)), unitShort(i.unitType) || "—"]),
      styles: { fontSize: 9, cellPadding: 5 },
      headStyles: { fillColor: [220, 53, 69], textColor: 255 },
      margin: { left: 40, right: 40 },
    });
  }

  // Footer on all pages
  const pageCount = doc.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setFontSize(8);
    doc.setTextColor(130);
    doc.text(`Generated by ${systemName} • ${now.toLocaleString()}`, 40, pageH - 20);
    doc.text(`Page ${p} of ${pageCount}`, pageW - 40, pageH - 20, { align: "right" });
    doc.setTextColor(0);
  }

  doc.save(`inventory-report-${now.toISOString().slice(0, 10)}.pdf`);
}
